### ISSUE TITLE
error in prepare step due to ambpdb output

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#23]
Dear Seekr2 team,
Just noticed that the ambpdb adds an additional line (CRYST1...) at the top of pqr files which causes the following error during the seekr2 prepare.py step (given [here](https://seekrtools.readthedocs.io/en/latest/tutorial_tryp_ben_hidr.html)).  After manually removing this line the calculation proceeds as expected.
Just thought to let you know in case it requires a bug fix.
Thank you

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Fatal error: exception Failure("wrong number of tokens at CRYST1   71.811   71.811   71.811 109.47 109.47 109.47")
terminate called after throwing an instance of 'Browndye::Jam_Exception'
  what():  Parse error at line 2 : no element found in file tryp_ben_receptor.xml
sh: line 1: 1226044 Aborted                 (core dumped) make_apbs_inputs /home/vaibhav/tryp_ben_hidr_tutorial/b_surface/apbs_input.xml > /home/vaibhav/tryp_ben_hidr_tutorial/b_surface/input.xml
Traceback (most recent call last):
  File "/home/software/seekr2/seekr2/prepare.py", line 75, in <module>
    model, xml_path = prepare(model_input, force_overwrite)
  File "/home/software/seekr2/seekr2/prepare.py", line 42, in prepare
    common_prepare.generate_bd_files(model, root_directory)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_prepare.py", line 961, in generate_bd_files
    runner_browndye2.make_browndye_input_xml(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/runner_browndye2.py", line 175, in make_browndye_input_xml
    debye_length = sim_browndye2.make_and_run_apbs(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_sim_browndye2.py", line 975, in make_and_run_apbs
    assert len(glob.glob(apbs_input_glob)), "Problem running " \
AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in

**Comment by lvotapka** [comment]
Thank you for letting us know - we might filter out CRYST lines or set up a check for this to give more helpful hints to users to remove this line from their PQRs.
