### ISSUE TITLE
Error running hidr.py

### ISSUE THREAD

**Issue by MissRaut** [seekrcentral/seekr2#33]
Hello Mr. Lane, Janvi here, Today I am performing calculations for another system. I got an error as follows , while running hidr.py script:  

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/software/seekrtools/seekrtools/hidr/hidr.py", line 366, in <module>
    hidr(model, destination, pdb_files, dry_run, equilibration_steps,
  File "/home/software/seekrtools/seekrtools/hidr/hidr.py", line 88, in hidr
    hidr_base.assign_pdb_file_to_model(model, pdb_file)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekrtools-0+untagged.65.g549ac37-py3.8.egg/seekrtools/hidr/hidr_base.py", line 352, in assign_pdb_file_to_model
    result = cv.check_mdtraj_within_boundary(traj, milestone.variables,
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/mmvt_base.py", line 365, in check_mdtraj_within_boundary
    radius = self.get_mdtraj_cv_value(traj, frame_index)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/mmvt_base.py", line 349, in get_mdtraj_cv_value
    traj2 = traj.atom_slice(self.group2)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/core/trajectory.py", line 1821, in atom_slice
    return Trajectory(xyz=xyz, topology=topology, time=time,
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/core/trajectory.py", line 1226, in __init__
    self.xyz = xyz
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/core/trajectory.py", line 939, in xyz
    value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/utils/validation.py", line 148, in ensure_type
    raise error
ValueError: xyz must be shape (Any, 32, 3). You supplied  (1, 33, 3)

Please help me understanding what is wrong here ?

**Comment by lvotapka** [comment]
Hello.

What is the exact command you are running? And can you share the PDB file you are trying to put in there? Can you share the model.xml and any other relevant files.

It seems to me most likely that a parameter/topology file has a different number of atoms than a PDB file that you are trying to put together.

In general, the more information and files you can provide for me, the easier and quicker it will be to figure out what is going wrong.

**Comment by MissRaut** [comment]
Sure sir , here is the command I am running, 

"#!/bin/bash 
#SBATCH - A     ##account name
#SBATCH -p GPU_NODES   #partition name
#SBATCH --nodes=1  ## number of nodes
#SBATCH --nodelist=node4    ###node lists
#SBATCH --ntasks-per-node=15  ## number os  processor core(s) per node
#SBATCH --job-name=JANVI   ##job name
#SBATCH --error=job.%J.err    ## any error during job submission or execution
#SBATCH --output=job.%J.out   ##any output after job execution

source /home/software/miniconda3/bin/activate
conda activate myseekr2

python3.8 "/home/software/seekrtools/seekrtools/hidr/hidr.py" any "/home/mschem/JANVI/janvi/tryp_ben_hidr_tutorial/model.xml" -M SMD -p lig_protein-solv.pdb" 

 here are some input files I am using - ( As these platform do not support the required file type I am converting it to .txt)
 
[model.txt](https://github.com/seekrcentral/seekr2/files/12358785/model.txt)

[lig_protein_solvatedpdb.txt](https://github.com/seekrcentral/seekr2/files/12358969/lig_protein_solvatedpdb.txt)

[lig_protein_solvatedprmtop.txt](https://github.com/seekrcentral/seekr2/files/12358970/lig_protein_solvatedprmtop.txt)

**Comment by lvotapka** [comment]
It looks like you attached the XML file as all three of these - the .pdb and .prmtop files aren't the right formats.

Did you try to see whether the PDB correctly matches the prmtop file?

**Comment by MissRaut** [comment]
ohhh Yes you were right , Actually by mistake I attached same .xml files as pdb and prmtop 

so here are the converted text files from .prmtop and .pdb i have been using .

[lig_protein_solvatedpdb.txt](https://github.com/seekrcentral/seekr2/files/12361766/lig_protein_solvatedpdb.txt)

[lig_protein_solvatedprmtop.txt](https://github.com/seekrcentral/seekr2/files/12361859/lig_protein_solvatedprmtop.txt)
]()

also I checked whether my  PDB atoms are Matching with prmtop file , hope you find it here

**Comment by lvotapka** [comment]
I just attempted to load the prmtop and pdb into VMD, and it indicated a mismatch between the number of atoms (45904 atoms in prmtop and 91776 in pdb)

**Comment by MissRaut** [comment]
Hello Sir, As you said earlier , there were some mismatch between the number of atoms in pdb and prmtop file so I prepared new pdb with same .prmtop & .inpcrd using ambpdb command.  Then used it as an input for hidr.py command still the error is same as earlier. 

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/software/seekrtools/seekrtools/hidr/hidr.py", line 366, in <module>
    hidr(model, destination, pdb_files, dry_run, equilibration_steps,
  File "/home/software/seekrtools/seekrtools/hidr/hidr.py", line 88, in hidr
    hidr_base.assign_pdb_file_to_model(model, pdb_file)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekrtools-0+untagged.65.g549ac37-py3.8.egg/seekrtools/hidr/hidr_base.py", line 352, in assign_pdb_file_to_model
    result = cv.check_mdtraj_within_boundary(traj, milestone.variables,
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/mmvt_base.py", line 365, in check_mdtraj_within_boundary
    radius = self.get_mdtraj_cv_value(traj, frame_index)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/mmvt_base.py", line 349, in get_mdtraj_cv_value
    traj2 = traj.atom_slice(self.group2)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/core/trajectory.py", line 1821, in atom_slice
    return Trajectory(xyz=xyz, topology=topology, time=time,
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/core/trajectory.py", line 1226, in __init__
    self.xyz = xyz
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/core/trajectory.py", line 939, in xyz
    value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/utils/validation.py", line 148, in ensure_type
    raise error
ValueError: xyz must be shape (Any, 32, 3). You supplied  (1, 33, 3)

here are my files :- 

[parp-olaparib-solv-prmtop.txt](https://github.com/seekrcentral/seekr2/files/12395424/parp-olaparib-solv-prmtop.txt)
[parppdb.txt](https://github.com/seekrcentral/seekr2/files/12395425/parppdb.txt)

**Comment by MissRaut** [comment]
ohh yes  , I will try correcting it , thank you for the response sir .
